---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: secure-tomcat
  labels:
    app: secure-tomcat-app
    env: dev
spec:
  replicas: 2  
  template:
    metadata:
      name: secure-tomcat
      labels: 
        app: secure-tomcat-app
        env: dev
    spec:
      containers:
      - name: secure-tomcat-container
        image: rajeshd2090/webapp:blue
        ports:
        - name: tomcat-port
          containerPort: 8080


