apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-10T17:37:40Z
  labels:
    app: secure-tomcat-app
  name: secure-tomcat-app
  namespace: default
  resourceVersion: "9729413"
  selfLink: /api/v1/namespaces/default/services/secure-tomcat-app
  uid: 2f73260a-ccb3-11e8-8569-0050568f3621
spec:
  clusterIP: 10.100.7.143
  externalTrafficPolicy: Cluster
  ports:
  - name: 8181-8080
    nodePort: 31939
    port: 8181
    protocol: TCP
    targetPort: 8080
  selector:
    app: secure-tomcat-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
